Repository sodacitylabs/rails-nodejs, pull requests merged in 2018-11, with the labels that each got.

#9 feat: router for incoming http requests
  package.json
  src/rails.js
Labels: :file_folder:

#10 chore: bump node version to do another release
  package.json
  src/rails.js
Labels: NodeJS

#11 feat: render module and render by default in view actions
  package.json
  src/rails.js
Labels: :file_folder:, ejs

#12 chore: isolate configurable values
  src/config.js
  src/rails.js
Labels: :file_folder:

#13 feat: send function for response objects
  src/rails.js
Labels: :file_folder:, NodeJS

#14 feat: unique guid for each http request
  package.json
  src/config.js
  src/rails.js
Labels: :file_folder:, NodeJS

#15 chore: cleanup dead code render function
  src/rails.js
Labels: :file_folder:

#16 feat(cli): parse body on post put requests
  src/rails.js
Labels: NodeJS

#21 feat: welcome aboard page
  src/config.js
  src/rails.js
Labels: NodeJS

#22 feat: handle root url via config
  src/cli.js
  src/rails.js
Labels: :file_folder:, NodeJS

#24 feat: eslint
  .eslintignore
  package.json
  src/.eslintrc.json
  src/config.js
  src/rails.js
Labels: :file_folder:, linting

#25 feat: prettier
  .gitignore
  .prettierignore
  src/config.js
  src/rails.js
Labels: :file_folder:, linting

#28 feat: initial routing errors page
  src/config.js
  src/rails.js
Labels: NodeJS, linting

#29 chore: add jest to core
  package-lock.json
  package.json
  src/cli.js
  test/.eslintrc.json
  test/rails.test.js
Labels: jest, linting

#30 Chore/file splits
  src/cli/index.js
  src/core/cli/generate/controller.js
  src/core/cli/new.js
  src/core/config/index.js
  src/core/index.js
  src/core/router/render.js
  src/core/router/send.js
  src/core/server/start.js
  test/rails.test.js
Labels: :file_folder:

#32 feat: install knex as dep
  src/core/cli/new.js
  src/core/config/index.js
Labels: :file_folder:, knex

#33 chore: install sqlite3 to project dependencies
  src/core/cli/new.js
  src/core/config/index.js
Labels: :file_folder:

#34 feat: generate model CLI
  src/cli/index.js
  src/core/cli/generate/model.js
  src/core/index.js
  src/core/model/base.js
Labels: :file_folder:, NodeJS

#35 feat: generate and connect to sqlite
  package.json
  src/core/cli/generate/model.js
  src/core/cli/new.js
Labels: :file_folder:, NodeJS, knex

#36 chore: bump to 0.4.0
  package.json
  src/core/config/index.js
Labels: NodeJS

#37 cli: db migrate command
  src/cli/index.js
  src/core/config/index.js
Labels: :file_folder:, knex

#38 feat: active record implement save
  package.json
  src/core/cli/generate/controller.js
  src/core/cli/generate/model.js
  src/core/db/index.js
  src/core/model/base.js
Labels: :file_folder:, NodeJS, knex

#39 chore: bump to 0.5.0
  package.json
  src/core/config/index.js
Labels: :file_folder:, NodeJS

#40 bug: only require db when asking for connection. bump to 0.5.1
  package.json
  src/core/config/index.js
  src/core/db/index.js
Labels: :file_folder:, NodeJS, knex

#41 feat: active record find
  src/core/model/base.js
Labels: :file_folder:, NodeJS, knex

#48 Set min Node version in package.json
  .nvmrc
  src/core/cli/new.js
Labels: :file_folder:, NodeJS

#51 Commit package-lock.json, use exact versions
  .npmrc
  package-lock.json
Labels: NodeJS
